name: ni_service
description: A new Flutter project.

publish_to: 'none'


version: 4.0.0+8

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  modal_progress_hud_nsn: ^0.4.0
  shared_preferences: ^2.0.6
  rflutter_alert: ^2.0.7
  intl: ^0.18.1
  fl_chart: ^0.41.0
  in_app_update: ^4.2.2
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/nilogo.png"
  android: true
  ios: true

flutter:

  uses-material-design: true


  assets:
    - assets/images/
