// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnvFrPI7_E9H4DPjdsfuLXmIH_tnTvWA4',
    appId: '1:945406651769:web:1f22531a2547a8f0bb93a8',
    messagingSenderId: '945406651769',
    projectId: 'ni-service-9755f',
    authDomain: 'ni-service-9755f.firebaseapp.com',
    storageBucket: 'ni-service-9755f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgijeqLDgtcoR1g13-W6OUoHOVGkFVXEY',
    appId: '1:945406651769:android:e28877b1e51315cfbb93a8',
    messagingSenderId: '945406651769',
    projectId: 'ni-service-9755f',
    storageBucket: 'ni-service-9755f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWxwDL39MoLBQ25KEP1g5EP8Sx_WeEhik',
    appId: '1:945406651769:ios:5744c14e3b4a1e5cbb93a8',
    messagingSenderId: '945406651769',
    projectId: 'ni-service-9755f',
    storageBucket: 'ni-service-9755f.appspot.com',
    iosBundleId: 'com.request.niService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWxwDL39MoLBQ25KEP1g5EP8Sx_WeEhik',
    appId: '1:945406651769:ios:828495552bc6f26dbb93a8',
    messagingSenderId: '945406651769',
    projectId: 'ni-service-9755f',
    storageBucket: 'ni-service-9755f.appspot.com',
    iosBundleId: 'com.example.niService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnvFrPI7_E9H4DPjdsfuLXmIH_tnTvWA4',
    appId: '1:945406651769:web:039052f3a87c99d8bb93a8',
    messagingSenderId: '945406651769',
    projectId: 'ni-service-9755f',
    authDomain: 'ni-service-9755f.firebaseapp.com',
    storageBucket: 'ni-service-9755f.appspot.com',
  );

}